package program;

public enum Diseases {
	Anemia,
	Diet,
	Bleeding,
	Hyperlipidemia,
	Disorder_of_blood_formation,
	Hematological_disorder,
	Iron_poisoning,
	Dehydration,
	Infection,
	Vitamin_deficiency,
	Viral_disease,
	Diseases_of_the_biliary_tract,
	Heart_Diseases,
	Blood_disease,
	Liver_disease,
	Kidney_disease,
	Iron_deficiency,
	Muscle_diseases,
	Smoker,
	Lung_disease,
	Overactive_thyroid_gland,
	Adult_diabetes,
	Cancer,
	Increased_consumption_of_meat,
	Use_of_various_medications,
	Malnutrition
}
